apiVersion: v1
kind: Secret
metadata:
    name: flux-git-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:aKZqT0u80PM3/A==,iv:sIrTT8Sd4nwoWXa9N4fxO5DsoWMB4LeqdmnVn6VebW4=,tag:MFdZMmeqWDSrqwppd+v1kg==,type:str]
    password: ENC[AES256_GCM,data:9c8PFnVMQ0U93/LQUTiYjw629g78K558avCcG0JL40Im31C2h1ioORmOptyhGV7qgIrCA3x+QgZH7Cuy1H+bc4p1bi3pBpTFWGAPjbLaaQvfAO8hCO3qzqQzJFvj,iv:bpynWt0nZuOE96ExAIFAlKmV2iWzsMkGPNkHixqpdPM=,tag:IIPhaV999s9rxZ/lbTgqJg==,type:str]
sops:
    age:
        - recipient: age1nvz70ympaeamwqp6rgvh7szctamvw70ft56ljlgzcf393thz8peqwsc3h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR0J1VXBrQjNmRXlsMVpW
            Y3RqODQzNW82S0xybE1JaFJqWWNSZVA5ZGlRClE5WjF6WHBFVjVLNkRZUlVueW0x
            NW90Tnk0WTRpY3FJL096Mk0wRnptTjAKLS0tIDY4elRBVFhNNzdGYk5IVVB1WGht
            a1Q0Q1Z4bVIvVFczUVE4c1BoaVBVaTgK9hYtN3n8d1E1inMVRlYYVncOgp/GDUJx
            TTcIi7qAXzVosJJU8IoFniVfdsKSZNdPQIaZFuAYI+34qOs+tDc7Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T10:23:04Z"
    mac: ENC[AES256_GCM,data:GG++SdX4cWWDhA8DfyD6IadphNFRUtEep6oPcqqbxbHzMZ6rEG8qheqKsm+PPpws17FIo6qZ8pNjo/22fjEqoqjqK32xck63vbPmLU/oZ4Sb1Ak4IV56N2UCCts24CMAe9Q/pyRzkLR9g45o+qB1ElhR07ZkwUYF11P0eJj5dKw=,iv:Gu7eEkSiD+Wr2GM29K7TuxaSDEFyTdZlokNS+y1281w=,tag:Ra9FTqnFH0O+wdcvYuPIFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
