apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:6q04+fQdQXuQuF8UsGuc/GXK4nZ/vCNJCjhjwflfHU5tJ0j29bFawuwo+i3lKGcYOr3ZLEW+MvDe12gY9WI/311Amg/zV8kBqjtFTToDNAysgx/vF74DmZ2k3GN+uGhV0jKoM2sSXZV30gvMRFoQpNNhba7IFJ0OEPcG+lu0poe97/Q/1pWWh4GFeKZ56ghUqP4ugWrV2SBJtRkOSWCKS8cGduLsx6IKAacsCWVRGOXX1kJWEtCm6p5dXmUZ9IAM8+iBCFNhxyaGTmlo/jxiNHMnvpVFX67GfnpRf4fvuFqasSz5nedc6sgbQeasMhkBvWIpd7Sj3NTjmKCCv4gcKSem7pd2XzJrHjRW5ENLf3+iwyRHedd7uCEQ+lssUHJVFxoAqKhFJpEIN1hoWgfbJwuyYXMwdEUTVXspeDH103fdgqAevy4AsI2gda4DI3rooCGgB4PIvG9rVdOkuqPpRExxW5eiEIe0KrU3hYwT56Wc31JLqiHpaZv2DoKjHrSRTIrsummHQ4tpp/uFaFOlrrAej2fawZJyD45VsjBURha3TvO5F16Rnz9mhF0J4sFlOhfaXqzrvbQqBbuYWaNNSVqUQ8zHxTVa4qpx2g==,iv:y87eW35IyCGPJBUf6oN173WSizls3B+T6azwfVQcQQI=,tag:HvCWXyuRsSE2Hil4w1BeEw==,type:str]
kind: Secret
metadata:
    name: ghcr-registry-auth
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1nvz70ympaeamwqp6rgvh7szctamvw70ft56ljlgzcf393thz8peqwsc3h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQUIrUWFEdkphVEpiODBC
            OVoxRlNtMTdZZlhjemdhNG9sdnZ4VmxVVVU0CnRvbEtFYkNvblJRNVhPMVBuZTNT
            ZEVSZWgySXJWWHRqNG9zcWdtQlZBc00KLS0tIGh5RXBlOG1Sbk83SXliRWlxcmNZ
            ekdIdUlkdWM1Y21OR1d2THFjdGlSQjQKKLyviIgP8roJ3zEXn3lr2hEbkH2sF3Ti
            N9u8FvPD0JeuRgNPy+TR9ijn0bZmDfetkSXDw8qtdVN/77eN7qUXxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T13:11:05Z"
    mac: ENC[AES256_GCM,data:b38Vum/JAeAGNcG8SVVDPi0qD80drVoUM5e6AZlK/ZkaAU1DaX53AFNiLBmSKBiAcjYt0rft0GcIZx568qvLbqhvHw3nIodQlw1jYL6ChLcVTeD22XWgyN1wGnEIys/HKi3Vr2P7+IBAR8WXFqtei0lo23Er2hViHEndWPIF3f4=,iv:vQuv67K0Q9Xh7WlvkQ/CfjVAe9CwMyOmCzoxi2h9q6A=,tag:HpjvrAeIQdK8YdSDvDMnVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
