apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:lK2Nbe6SxuM6I9zvrt8GwY7esU0TlFjQGiTMdK2VTVEI/SDpIhtHqOAKetzVvsbmora6eqEe4/Wga5otXRoJpazTT8T0HZdc+h8proWKGFBA5Xg9yEJ8J3UhLpc3w2eDdA1+c40AkaKqEaiuQUJa5FqPWbSzF/CaZTuRWVQmUzRXlTBgzJQ/qcNizy2NRLW8ur/LNLyaQSvSVUrrUWLFXHZKdvjKX1K0CKyIbV+8cG+yxlr0+AJ8Skr/TVuOwS3vB1rboqnwkkOuQuWXB8iMT39dfmfilOA55LkE9/ujxpge0k2EDhrlP6NdtOXfwFP3dC5VJGzSLU6o7saEbcwrUr3mD8vimw2JyTclb619gzLIeLB81LfbzyUSbCowXD4UB8nJLRlWpsRDlxYO5dEQip/ObNyqfwokhiyCSpifODHDaDtn2uiHY/NJJfCi8JGvegvvzVl5jVUtOciwjXSPhQH5Gvm65u7E2aZzd12gVdySaZWGrN/SHbArzqXYIjbnVW4Ig/gJP7h6r2QFIKgP1v7TjsXTVNCz94+TE+1J+q2J5L7Mv3NYSNjxu/JF5uE8ejSEKyl0qBS2XPxsjtViM/sAhAt0WyIYJHFRFg==,iv:6ViQ/CJQpvVJupRzQTQs5jkw8n4g5xIlotFZkHGmCmo=,tag:PXDIbhR0EwcRDticFTGAbg==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: dev
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1nvz70ympaeamwqp6rgvh7szctamvw70ft56ljlgzcf393thz8peqwsc3h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArS3dUcU9BbDZjOVRTYkVK
            Nm15cDFSQkkyRjNzNW5tMVF3MDFYaDYyYmljCmpqdFRjS29BT0szcHlWNElPZUh6
            bnNEVVpYMUFxbEtxc0NObE5zMVR1aXMKLS0tIEorV04yTnJ3REtUMjE3WGxPeTl5
            Y2NRbkJSZkFzajNCUjZyZElnQVY5cEEK8ODNEJQ1Bg4h1DZhAjEE0ZAmHTAJHp6h
            DmbgPoQwr01hgS3qH4K4QH0tEf6MNC/DCYlXO2m8xPofdJAz0gIAAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T12:58:05Z"
    mac: ENC[AES256_GCM,data:AEFN9KedDoIbIEwyi9t8qXV5zUWs9c8EfUYVasIDXLWrOcnRkjL8ixbh4HBc8NHCnalsvtc/2q+mRyWbfP/BFrTTGUeIbZdz93a3g60q188klWq1sCPuvvNhbYf64aY5t6cM/+pCwdTFXlSC+2p1nI1xWymZ0g4qs0jgT6EZaaE=,iv:lfI4ex0/AqFX8XJ+qaRDS/2kVdVvdQb2Ri+f0sy+pBs=,tag:qGyv9CgKCM9nvJvd0Fa+Ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
