apiVersion: v1
kind: Secret
metadata:
    name: ghcr-registry-auth-dev
    namespace: dev
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:mTeC/8PpWrapMtZuPo/VJAGbHcL1VodxzLmmqNbqiHd8R8t6W7ICbVjkJMuC/sE9kcskusMPZwDApl375Axt5waPGq04QUFti1bl2sr+9i5EDAm/laIZTVVNAlG6+iGLe38TY4CzHYCiGNeyCA2aORBFCb+V9IVM62U4VlcPVnM8OBkhf/m5szwi0YBxw97XH5Y3Vtcbf4VyfDKfMqIOaFlioQI1BapAI0vmJw==,iv:l0eAyReu1WGvoJ1TyadFkWYtrD4xdBHj3+StmkazF+U=,tag:prhF4bdCOfB/fv4EUaT2bg==,type:str]
sops:
    age:
        - recipient: age1nvz70ympaeamwqp6rgvh7szctamvw70ft56ljlgzcf393thz8peqwsc3h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseTNQRVRFVWRWUm1iK0ti
            L2VCeDQvRUZkRWhUUHJUMnZOdTFqWko4Z2dVClEvUktUeGwvTTNiSkZrVlJZSnRy
            em1oWWt6bXFEWDNLVXlRM3RBaWFGVmcKLS0tIDlUb2NGbTE5TzduQU9CSWtVN1dD
            WW1HZTJ2Zk1XZm9SZ3VaeTBpV3Q5d0EKxjdx+V461rnkKxnwGthZLbnC3PyAt1Gk
            V4LZYNBrp9z7HPL/djQQ3kuRwogv8f6pzOHlEm06BUK1tX6kq74gAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T15:53:47Z"
    mac: ENC[AES256_GCM,data:qmWAXOpzEm2++uwtqKFczxzxh1l6HKxOCDj8U45vbKsr94y9OW172tuLEqN2yynLa1va3tnW7OSliNDgGXiOEUpVBGwnssS4yER3AQCCVpO4QwxjIhAFJ8o6L04sHj80pjC+rpBSwV7qQiydEq+oHYeQXXX9lya+ZFaVzI8/UQ4=,iv:3gNiW3xpjPnri+ktseZ/BCMSbUIfa+F0kmj0gzCYtvA=,tag:5irqXIB7GsYwVZJFOe+FLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
