apiVersion: v1
kind: Secret
metadata:
    name: ghcr-registry-auth-dev
    namespace: dev
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:NUB/j2TbQCHYhibeloWwxNEKDvU1K31yytNT4BezS6ETFtOmXWeSnT5S50qRUef+y2JakArdAKroZS23/gwETVOs5jO68BaL1uNx7qXIQbEZhC+bRss1o3eLgxsc6DtoPP/t3vEviC2slMKt0VBcV2VdzbrvvH80rzEizr9N67JFWMfsbzGFxZckBQ+TynxiPIiUd0SUnAeogXan9vMgtpO0DH12IsOaxmOLjA==,iv:IZUFg76uDLI02BgyIf6ttHr2ZK01/0OnJT08QPaWZok=,tag:33m3InfX3iYwLAdkiynhWg==,type:str]
sops:
    age:
        - recipient: age1nvz70ympaeamwqp6rgvh7szctamvw70ft56ljlgzcf393thz8peqwsc3h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRnY5S2I2Q00xNUduSDRY
            dXc4NzhMZG9LK1R2Mi91aHVuYVovd1RCckdvCiszS0xOOHVDZFh0K29pWVdiMHV2
            VFg4cDdtL2xSdWxoaDliTTR5R0VVencKLS0tIGZoa2RpZGhoWS81RVNnOUN3SERw
            NVJSa3pmam5Fc3hUcHZNZ0lqTVp3WGcKALtOzIDtOau8xQkaxs7TwOWMumRBD06s
            hNNmQ/p4q918hPfCVMEqHIf12xPI+pkhJszbw6Du6JzqfA4g3BseqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T10:01:07Z"
    mac: ENC[AES256_GCM,data:4gsXgFI2mNuQBagmj+rEoQbbvIUfUxbvqReJqpbycHq3woRH80cMOQ/reI5PLYNIYlitwNqsJBWTeVrdS7NVYYRnJmlSprJnhDB6aD3MBLxtcCCpwTKMtBhI0aeOCafC0Ak4Sp1bGxxRFySaDU2WQOBY1//3McHhZPpyUfOZbcI=,iv:EwCcCLhIA75GrxzuPsqeQBQJSI9WgyHHngM2ttTjQFA=,tag:mi508gCL/LtX4kuXyBKbYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
