apiVersion: v1
kind: Secret
metadata:
    name: ghcr-registry-auth
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:1EdbwA02iRjIwMaouHGP6448HD31iB5xfzdXLXui8c4sJ6I8dU1m610o1p52FqE3nzlTaujw3aZfMX6EGOYL+n/OORb0aIoxzrWi+3oAYSu6k6zw0qzeqKo22Fp4PJ8iwBVCrHmkBlZBGgYvl5gFx8kH02EDwALkxakBzi4vd0i+90IJvPcrpJ95gFgHoFRLLkl8scSVOd3SJ4gvDxffY/2AnBsxK9gQWNTFjMpsWRqJ2uCsUpBoUGEiZmfAReCYLfMfGdt43todS662JwqwO4ZWj+Y5Q478cPPpnrODA37f,iv:pMGDAzWZB+wRJ4IXTOQp6tRHRoEvgK3ubiXfETqoHDQ=,tag:50BLTZqqlyHR5kAwfs5mRQ==,type:str]
sops:
    age:
        - recipient: age1nvz70ympaeamwqp6rgvh7szctamvw70ft56ljlgzcf393thz8peqwsc3h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQmdya1Z2QnJmdzhtdjNa
            NVlWdTR1QTRBaDNJRjNVN2NUams5QlUxWWc4CkZsKzgxWEhaYU1TK0xidm9BVVZS
            Vy8wN0VicWkvY0x0RUI5MGttZmJ0enMKLS0tIGVsVVk5Y3BPb3FpczFEandiOW9t
            Rzl1QTVWVktyMTU5VU8ya3RiZVFQZjQKxKJU8DG9vlWiGTfEBSL4vZZvBWZJil4h
            HkuiFRlx+BkqdsFcVyWceLyuv6F6Yg7tZwI/zFyCcv/NcPZwAzwEGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T11:33:46Z"
    mac: ENC[AES256_GCM,data:ybPyKJ8vvJDeWCmjXuM2XBEIQ41JZJp5Z4clHXwT8t9whzMaouwSQjHJ2EAnGa6leVzwCO5w1cDGaWMxVJ/lWot5lv1TIuofXe6HXwWTISIqvlmNVgZw9RuaWJ4xhMoanWw+zqM07NozJE3G0cpNNWexlFUbVJwClYjyHA54+nw=,iv:7pUhI7urClZTsElCZORhapR1GMOwPzpX9VqGupzz5Ug=,tag:+X0j1T3wkMW8AxfXhZUGPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
