apiVersion: v1
kind: Secret
metadata:
    name: ghcr-registry-auth
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:X6YsWNaefayEsgQGsOIIHSy1+pUGekAWJKshDMTebLL/PeWUArJPt6qCky2Ae3+/jWc9raaALqNrPit3kdJ+dibLyDrsHUeZdJcUsNwspIO+BHLDRyU2+/eq2/u3N1lzFO2S4N2700IAcy4El8OlS7SZadI2UB+ZADVorjlF6/gcJy3jXXMyOTTRGBXloVW5dLZZLhcrJJX8JWga7KgnYs0y26kzXsb2JbVMCg==,iv:1jF5PTJ0MgtZ+7aVsiW70Sf4LK7zTMieDEfICqlv8Bg=,tag:/Di9z9jNspS8wUqy9mRBBg==,type:str]
sops:
    age:
        - recipient: age1nvz70ympaeamwqp6rgvh7szctamvw70ft56ljlgzcf393thz8peqwsc3h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UEtCSzhiT3VrNzZRSWVr
            SUNYZU82bHo2enNrMVh3TkVFdmxnS2hYdWxvCi9aSmJUK3FReDkxWC84c3pIYVJh
            R20vQ2paSkQ3UmhJYVd5Vi9TbXpycXcKLS0tIHZwUjFwUmttQ1UyMmhnWjRJNTRl
            MkphblY0d09sZFRzcFRwV051eHM1WlUKbq92Zu55Uwj3seQzRNlBtbUqDSgDbgNr
            kj5Oql4w1/pHN55bGE/Gkgovozpo6DcsLodKL22QPsuYAJTguJE6iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T15:53:13Z"
    mac: ENC[AES256_GCM,data:J6XPPHhhFhcTAxwwCQeQ0pI37EFp7JO6z9pkT3E0dhyVSKZIhVg2dOAkPWjRqvxT/cvMibRvMOe23r3yjFDTDU1cXu8F7R4T1Z8YXASteX8AlKaz/ixdnKMnb2JUIPa2siffcQ2LEnXcDVwvGH2cUpLLyXEDoKDPkf7NQvuv5dQ=,iv:nkqWx3qT8vCB23ykBotZDDwWJjDXgHapeeLxW+eGtYQ=,tag:twyYVdTQGghytyBJRRd1AA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
