apiVersion: v1
kind: Secret
metadata:
    name: ghcr-registry-auth
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:W3vBGzv2sGR4W1SeCH3r7gQUD9GOtuQ6FAVx95aEsGcyra/M2R6D93U4SXKTBQB95c+m2jkwQNo5YfA8FoVgEGjKEG/22ut0ZJErEIXv+ewbtSMSbXoTdbo3INbyW30B11S+7/4cIRpxy3JPib4CCS7AWK3xWi12dGnmV/3qOg8br1YU+VBB1NKQ6wto6jFuqkgHWdtHeGtO3hn9EA7ChGk6nQFA/JdVv4a7BA==,iv:xajKly2A/G45HEwW0eHXE0me1VSyP8eDuPGeAs4LMM4=,tag:OpiHG2C6GCRMJo6JfNAgvg==,type:str]
sops:
    age:
        - recipient: age1nvz70ympaeamwqp6rgvh7szctamvw70ft56ljlgzcf393thz8peqwsc3h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcGR2d2Z5S1Y3NXRoVW5l
            NnU3aWxGS1BSTTRFWUhjNkloVHdzWWhBNmhNCjcxUFdsQUlBYkpVUXF2NC9kMkpK
            UWNkdEhETFRXd3lUOHR5MisrYlA3VGsKLS0tIFh5L3h0eUNIMnZON3kramttWVQ1
            aTNYdnYwaGFUUXdGK0tDTXlsUEJMdDAKjIbB8N9Qoodbv/4g81y/EcIygUFIsDs9
            VtFXZYnG9xo5KMcEouGdgaAnA7d0/rYswdTIDxIYMNzDbZPiXZyELA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T13:45:57Z"
    mac: ENC[AES256_GCM,data:FtgBcAB2rl4W+4ak55NpBORDaSlF+RR0wUjLK1+9c3wHZRThsWMYSHLvuZ2QV5gPVmULCCTS0BuRava9zo9zBwJQubEjypmXkVH++NeGkzzcJAjKpz8o0DDhPcBEVLP4MBwnC9vcdFgBIPuA6msE+cUuDl0S6IEbLIMychmkM1Y=,iv:DFlSBh1p5er7gzmMUxIG0ong8OE14ksO8j3GaoAuqmY=,tag:olf1NZafrnwxGkRGq4hWDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
