apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: ghcr-registry-auth-dev
      containers:
        - name: myapp
          image: "ghcr.io/sergiioocs/python-api-cicd-testing:main-960d693-1778397674"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
