apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: ghcr-registry-auth
      containers:
        - name: myapp
          image: ghcr.io/sergiioocs/python-api-cicd-testing:main-f23d2c9-1777473955 # {"$imagepolicy": "flux-system:myapp"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
