apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/placeholder/placeholder
    newName: ghcr.io/sergiioocs/python-api-cicd-testing
    newTag: ghcr.io/sergiioocs/python-api-cicd-testing:main-2248ce8-1777471889 # {"$imagepolicy": "flux-system:myapp"}
