apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/placeholder/placeholder
    newName: ghcr.io/sergiioocs/python-api-cicd-testing
    newTag: "main-44878a2-1777474480" # {"$imagepolicy": "flux-system:myapp"}