apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/SergiiooCS/python-api-cicd-testing.git
  ref:
    branch: main
  secretRef:
    name: flux-git-auth