#!/usr/bin/env python3

#SCRIPT DE PYTHON QUE COMPRUEBA QUE LAS VARIABLES DE ENTORNO EXISTAN Y TENGAN VALOR (QUE SU VALOR NO SEA NULL O NONE).
import os
from pathlib import Path

#CREO UNA LISTA DE PALABRAS SENSIBLES, EL NOMBRE ESTA EN MAYUSCULAS PORQUE ES UNA CONSTANTE.
PALABRAS_SENSIBLES = ["TOKEN", "KEY", "SECRET", "PASSWORD", "CREDENTIAL", "PASS"]

#FUNCION QUE COMPRUEBA PALABRAS SENSIBLES
def is_sensitive_variable(name):
    name_upper = name.upper()
    
    for word in PALABRAS_SENSIBLES:
        if word in name_upper:
            return True
    
    return False

"""
A LA FUNCION LE PASO EL NOMBRE DE LA VARIABLE DE ENTORNO QUE QUIERO COMPROBAR SI ES SENSIBLE O NO.
EL NOMBRE DE LA VARIABLE SE CONVIERTE A MAYUSCULAS PORQUE LAS PALABRAS SENSIBLES EN MI LISTA ESTAN EN MAYUSCULAS.
RECORRO LA LISTA DE PALABRAS SENSIBLES Y COMPRUEBO SI LA PALABRA QUE LE HE PASADO CONTIENE EL VALOR/APARECE DENTRO/PERTENECE A LAS PALABRAS SENSIBLES DE LA LISTA.
EJ: SI LE PASO 'GITHUB_TOKEN' A LA FUNCION, ESTA PALABRA CONTIENE EL VALOR 'TOKEN' QUE YO TENGO EN LA LISTA DE PALABRAS SENSIBLES, POR LO TANTO LA FUNCION DEVOLVERA TRUE.
AL USAR 'RETURN' SALE DE LA FUNCION. DE NO SER 'TRUE' EL RESULTADO, DEVOLVERA 'FALSE' Y SIGNIFICARA QUE LA VARIABLE DE ENTORNO NO ES SENSIBLE.
"""

#FUNCION QUE OCULTA EL VALOR DE LA VARIABLE SI ES SENSIBLE
def ocultar_valor_variable_sensible(name, value):
    if is_sensitive_variable(name):
        return "****"
    return value

"""
A LA FUNCION LE PASO EL NOMBRE Y EL VALOR DE LA VARIABLE DE ENTORNO QUE QUIERO OCULTAR SI ES SENSIBLE.
LA FUNCION LLAMA A LA FUNCION 'is_sensitive_variable' PARA COMPROBAR SI LA VARIABLE ES SENSIBLE O NO.
SI LA VARIABLE ES SENSIBLE, DEVUELVE "****" EN LUGAR DE SU VALOR REAL. SI NO ES SENSIBLE, DEVUELVE SU VALOR REAL. DE ESTA MANERA, SI IMPRIMO LAS VARIABLES DE ENTORNO, LAS VARIABLES SENSIBLES NO MOSTRARAN SU VALOR REAL, SINO "****". ESTO ES IMPORTANTE PARA EVITAR EXPONER INFORMACION SENSIBLE EN LOS LOGS O CONSOLA.
"""

#FUNCION QUE RECORRE TODAS LAS VARIABLES DE ENTORNO.
def get_all_env_variables():
    print("=== VARIABLES DE ENTORNO DISPONIBLES ===")
    for name, value in sorted(os.environ.items()):
        value_oculto = ocultar_valor_variable_sensible(name, value)
        print(f"{name}: {value_oculto}")

"""
LA FUNCION RECORRE TODAS LAS VARIABLES DE ENTORNO DEL SISTEMA.
CREO LA VARIABLE 'value_oculto' QUE ALMACENA EL VALOR DE LA VARIABLE DE ENTORNO. CON LA FUNCION 'ocultar_valor_variable_sensible' COMPRUEBA SI EL VALOR DE LA VARIABLE ES SENSIBLE, DE SERLO DEVUELVE '****' Y SI NO LO ES DEVUELVE DIRECTAMENTE EL VALOR.
MUESTRO POR CONSOLA EL NOMBRE DE LA VARIABLE DE ENTORNO Y SU VALOR (OCULTO SI ES SENSIBLE).
"""

#FUNCION PRINCIPAL QUE LLAMA A LA FUNCION QUE RECORRE TODAS LAS VARIABLES DE ENTORNO
def main():
    get_all_env_variables()
    print("=== FIN DE LAS VARIABLES DE ENTORNO ===")
    
if __name__ == "__main__":
    exit(main())
"""
EN PYTHON CUALQUIER ARCHIVO SE LE DENOMINA 'MODULO'.
CUANDO SE INTERPRETA ESTE 'MODULO' AUTOMATICAMENTE SE CREA LA VARIABLE '__name__' QUE CONTIENE EL NOMBRE DEL MODULO.
LA CONDICION ES: SI EL NOMBRE DEL MODULO ES IGUAL A '__main__', SIGNIFICA QUE ESTE MODULO SE ESTA EJECUTANDO DIRECTAMENTE.
'__main__' ES EL NOMBRE QUE PYTHON ASIGNA AL MODULO PRINCIPAL QUE SE EJECUTA.
"""
